### ISSUE TITLE
言語を決める

### ISSUE THREAD

**Issue by m1sk9** [BattleFieldJapanCommunity/Site#2]

**Comment by narusenia** [comment]
フロントエンドの実装は
**HTML JS Sass + Gulp**
で行こうと思うんですがどうでしょう

**Comment by m1sk9** [comment]
良さそう

**Comment by NaruseNia** [comment]
了解です。こっちはそれで進めていきます

**Comment by m1sk9** [comment]
tksさん把握してる？

**Comment by narusenia** [comment]
> 良さそう

了解です、一応フロントエンドはこれで進めていきたいです

**Comment by m1sk9** [comment]
![image](https://user-images.githubusercontent.com/82575685/130180937-f2ba7b92-08c0-4b45-af37-b30fc9dfbeff.png)


これにて決定
